"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var charts_module_1 = require("./charts.module");
exports.AdChartsModule = charts_module_1.AdChartsModule;
var card_component_1 = require("./card/card.component");
exports.ChartCardComponent = card_component_1.ChartCardComponent;
var mini_area_component_1 = require("./mini-area/mini-area.component");
exports.MiniAreaComponent = mini_area_component_1.MiniAreaComponent;
var mini_bar_component_1 = require("./mini-bar/mini-bar.component");
exports.MiniBarComponent = mini_bar_component_1.MiniBarComponent;
var mini_progress_component_1 = require("./mini-progress/mini-progress.component");
exports.MiniProgressComponent = mini_progress_component_1.MiniProgressComponent;
var bar_component_1 = require("./bar/bar.component");
exports.G2BarComponent = bar_component_1.G2BarComponent;
var pie_component_1 = require("./pie/pie.component");
exports.G2PieComponent = pie_component_1.G2PieComponent;
var timeline_component_1 = require("./timeline/timeline.component");
exports.TimelineComponent = timeline_component_1.TimelineComponent;
var gauge_component_1 = require("./gauge/gauge.component");
exports.GaugeComponent = gauge_component_1.GaugeComponent;
var tag_cloud_component_1 = require("./tag-cloud/tag-cloud.component");
exports.TagCloudComponent = tag_cloud_component_1.TagCloudComponent;
var water_wave_component_1 = require("./water-wave/water-wave.component");
exports.WaterWaveComponent = water_wave_component_1.WaterWaveComponent;
var radar_component_1 = require("./radar/radar.component");
exports.G2RadarComponent = radar_component_1.G2RadarComponent;
var chart_component_1 = require("./chart/chart.component");
exports.ChartComponent = chart_component_1.ChartComponent;
